### ISSUE TITLE
Extracted key seems wrong

### ISSUE THREAD

**Issue by BenjaminSoelberg** [0vercl0k/stuffz#6]
When compiling and running wbaes128_attack_the_boxes the following key is extracted:
\x30\x76\x65\x72\x63\x64\x30\x6b\x40\x64\x6f\x61\x72\x65\x2d\x65
The ascii version is : 0vercd0k@doare-e
I would have expected  : 0vercl0k@doare-e

Is it possible that the method isn't 100% and more than one possible key should have been returned ?

**Comment by 0vercl0k** [comment]
Thanks for spotting this Benjamin - sounds like I've wrote this code 2
years ago according to the github history so I am not able to answer your
question from the top of my head; there just might be a bug in my code.
I'll try to re read the associated post and see if I can debug this in the
next two weeks!

Cheers,
Axel

2017-08-15 14:31 GMT-07:00 Benjamin Sølberg <notifications@github.com>:

**Comment by 0vercl0k** [comment]
Hey @BenjaminSoelberg - I fixed the issue you reported; basically I forgot
a step when right shifting of 8 bits the second line of the matrix :). Also
found this typo while debugging:
https://github.com/0vercl0k/stuffz/commit/34dd7a92b5435c8efd4d032600b2935c2342c54c
.

```
D:\Codes\wbaes_attack\wbaes128\wbaes128_attack_the_boxes>D:\Codes\wbaes_attack\wbaes128\Release\wbaes128_attack_the_boxes.exe
Key successfully extracted & UnShiftRow'd:
\x30\x76\x65\x72\x63\x6c\x30\x6b\x40\x64\x6f\x61\x72\x65\x2d\x65

In [14]: '\x30\x76\x65\x72\x63\x6c\x30\x6b\x40\x64\x6f\x61\x72\x65\x2d\x65'
Out[14]: '0vercl0k@doare-e'
```

Cheers

2017-08-15 19:15 GMT-07:00 0vercl0k <0vercl0k@tuxfamily.org>:
