### ISSUE TITLE
[+] something maybe should change in "ghetto-iongraph.py"

### ISSUE THREAD

**Issue by ghost** [0vercl0k/stuffz#9]
Hey, Thanks for your sharing. I use ghetto-iongraph.py to generate the mir graph in ionmonkey. It's very useful.

But I think maybe a little thing maybe should changed.

-   "-s" option .

![image](https://user-images.githubusercontent.com/34005655/90861260-10996080-e3be-11ea-84d9-918d351607a8.png)

on line "475", we do something like "./js -s ....". In the newset js shell. The "-s" option been removed(seems)... 

 
![image](https://user-images.githubusercontent.com/34005655/90861508-6a018f80-e3be-11ea-951c-eb0f15da1ae6.png)

-  unicode error

When I use this script. As a Chinese user, The path "c:\usr\wjllz". seems \u \w will be "escape"...

![image](https://user-images.githubusercontent.com/34005655/90862286-cdd88800-e3bf-11ea-9367-e4aaa2dc7fd6.png)

I use a replace function make it work....

![image](https://user-images.githubusercontent.com/34005655/90862419-fbbdcc80-e3bf-11ea-9e2c-e1fdb0e071f4.png)

-   Can't show the gv file in the html file

When I open the index.html file, I can't see anything(I guess maybe it is because of that the gv file is too large....)

![image](https://user-images.githubusercontent.com/34005655/90862654-52c3a180-e3c0-11ea-8b9f-21b93b625638.png)

And I use "dot -Tpng xx.gv -o xx.png "... maybe png file will be better? I don't know too much about this...

Thank u very much, best wishes!

**Comment by redogwu** [comment]
Hey, Seems the third problem is easy to solve. 

When I open the index from the by click it. seems the security property by browser will disable us fetch the a file from "file//c".
seems it is named "cross site?".
![image](https://user-images.githubusercontent.com/34005655/91137065-14d8bd00-e6e1-11ea-9795-fc6489701dad.png)

So I use python to create a local server. 

 >        python2.exe -m SimpleHTTPServer

Obviously, it works!
![image](https://user-images.githubusercontent.com/34005655/91137330-2752f680-e6e1-11ea-8680-5b29c33a39fa.png)

Would u mind add this tips to your readme file. I think it maybe useful fro another. Thank u.

Cheers!

**Comment by 0vercl0k** [comment]
Oh I see - glad you figured it out!

Cheers
